// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestCaseApi.Data;

#nullable disable

namespace TestCaseApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestCaseApi.Models.TestCaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("EvalDurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("eval_duration_ms");

                    b.Property<string>("Expected")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected");

                    b.Property<string>("Framework")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("framework");

                    b.Property<double>("LatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_used");

                    b.Property<double>("PromptEvalDurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("prompt_eval_duration_ms");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requirement");

                    b.Property<string>("ScriptCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("script_code");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("steps");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<double>("TotalDurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("total_duration_ms");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.HasKey("Id");

                    b.ToTable("test_cases");
                });
#pragma warning restore 612, 618
        }
    }
}
