// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestCaseApi.Data;

#nullable disable

namespace TestCaseApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestCaseApi.Models.TestCaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Expected")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected");

                    b.Property<string>("Framework")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("framework");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_used");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requirement");

                    b.Property<string>("ScriptCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("script_code");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("steps");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("test_cases");
                });
#pragma warning restore 612, 618
        }
    }
}
